name: Generate ASCII Artwork


on: push

jobs:
    first_job:
        runs-on: ubuntu-latast
        steps:
        -  name: Checkout Repo
           uses: action/checkout@v4

        -   name: List files
            run: ls -ltra
    
        -   name: Executing Shell Script
            run: ./ascii-script.sh
