name: WorkFlow filters and activities
on:
    workflow_dispatch: 
    push: 
        branches-ignore:
            - feature/*      # feature/add-music , feature/updateImage
            - test/**        # test/ui/index ,test/checkout/pyment
        branches: 
            - main
            - '!feature/*'   # ignore pushing to any bransh name starting with feature using !
    pull_request: 
        types: 
            - opened
            - closed
        paths-ignore: 
            - README.md       # workflow will only run when a pull request that includes a change on any file other than README.md 
        branches: 
            - main            # configures your workflow to only run on pull requests that target specific branches.

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - run: echo this workflow/job/step is executed for type -${{github.event_name}}
    